#server port
server:
  port: 8000
  context-path: /blog
spring:
  thymeleaf:
      cache: false
      encoding: UTF-8
      mode: HTML5
    #    prefix=
    #    settings.*=
    #    suffix: .html
    #    template-loader-path=classpath:/templates/ #comma-separated list
    #    view-names= # whitelist of view names that can be resolved
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lazydsr-blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true